
<h1 style="text-align: center"><b>Getting the Store Information</b></h1>

<h2><b>Store Id:</b> <?php echo $block->getStoreId() . '<br />'?></h2>
<h2><b>Store Code:</b> <?php echo $block->getStoreCode() . '<br />'?></h2>
<h2><b>Website Id:</b> <?php echo $block->getWebsiteId() . '<br />'?></h2>
<h2><b>Store Name:</b> <?php echo $block->getStoreName() . '<br />'?></h2>
<h2><b>Store Url:</b> <?php echo $block->getStoreUrl() . '<br />'?></h2>
<h2><b>Store Active:</b> <?php echo $block->isStoreActive() . '<br />'?></h2>
