<?php
/** @var \Magento\Framework\View\Element\Template $block */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$urlInterface = $objectManager->get('\Magento\Framework\UrlInterface');

$baseUrl = $storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB);
$currentUrl = $urlInterface->getCurrentUrl();
?>

<div>
    <strong>Base URL:</strong> <?php echo $baseUrl; ?>
</div>
<div>
    <strong>Current URL:</strong> <?php echo $currentUrl; ?>
</div>
