<?php
$cmsPage = $block->getCmsPageDetails();
if ($cmsPage):
    echo "<h1>Page Title:" . $block->getCmsPageTitle() . "</h1>";
    echo "<h2>Page SubTitle: " . $block->getCmsPageSubtitle() . "</h2>";
    echo "<h2>URL Key: " . $block->getCmsPageUrlKey() . "</h2>";
    echo "<h2>Content Heading: " . $block->getCmsPageContentHeading() . "</h2>";
    echo "<h2>Page Content:</h2>";
    echo $block->getCmsPageContent();
else:
    echo __("CMS page not found.");
endif;
?>
